name: timESD
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pytorch-lightning=1.2.3
  - pytorch=1.7.1
  - scipy=1.6.1
  - nano
  - pandas>=1.2
  - numpy
  - matplotlib
  - git
  - tqdm
  - tensorboardx=1.9
  - neptune-client
  - hydra-core>=1.0.6
  - omegaconf
  - pyaml
  - scikit-learn
  - pip
  - pip:
      - omegaconf>=2.0.6
      - torchmetrics
      - scikit-metrics
      - pretrainedmodels
      - pytorch-lightning-bolts
      - nvidia-htop