setup:
  project_name: template/LSTM
  experiment_name: LSTM
  tags: LSTM
trainer:
  default_root_dir: ./
  gpus: -1
  precision: 16
  stochastic_weight_avg: False
  val_check_interval: 1.0
  overfit_batches: 0.0
  fast_dev_run: False
experiment:
  filepath: /data/
  seq_len: 96
  n_features: 4
  hidden_size: 128
  num_layers: 3
  dropout: 0.5
  learning_rate: 0.01
  batch_size: 128
  num_workers : 8
