setup:
  project_name: thbuerg/timESD
  experiment_name: debug
  tags: LSTM
trainer:
  accumulate_grad_batches: 1
  stochastic_weight_avg: False
  val_check_interval: 1.0
  overfit_batches: 0.0
  fast_dev_run: False
  gpus: 3
  max_epochs: 2000
experiment:
  max_epochs: 2000
  seq_len: 672
  n_targets: 52
  n_features: 4
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 128
  num_workers : 8
